elasticsearch:
  image: eason02/elasticsearch:5.0.1
  container_name: elasticsearch-image
  restart: always
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - /root/elasticstack/elasticsearch/logs/:/usr/share/elasticsearch/logs
    - /root/elasticstack/elasticsearch/data/:/usr/share/elasticsearch/data
kibana:
  image: eason02/kibana:5.0.1
  container_name: kibana-image
  restart: always
  ports:
    - "5601:5601"
logstash:
  image: eason02/logstash:5.0.1
  container_name: logstash-image
  restart: always
  ports:
    - "5000:5000"
  volumes:
    - /root/elasticstack/logstash/logs/:/var/log/logstash
